[theme]
  theme = "plain"

[theme.overrides]
idle_bg = "#8b7355"
idle_fg = "#e6d9b8"
info_bg = "#8b7355"
info_fg = "#e6d9b8"
good_bg = "#8b7355"
good_fg = "#e6d9b8"
warning_bg = "#8b7355"
warning_fg = "#e6d9b8"
critical_bg = "#cc0000"
critical_fg = "#000000"
separator = "|"
separator_bg = "#8b7355"
separator_fg = "#e6d9b8"

[icons]
  icons = "~/.config/i3status-rust/icons.toml"

# Battery
[[block]]
block = "battery"
format = " $icon $percentage"
full_format = "$icon"
empty_format = " $icon $percentage"
charging_format = " $icon $percentage  "
not_charging_format = "$icon $percentage  "
interval = 10

# Backlight
[[block]]
block = "backlight"

# Bluetooth
[[block]]
block = "bluetooth"
format = "$icon $percentage"
disconnected_format = "$icon"

# Volume
[[block]]
block = "sound"
driver = "alsa"
show_volumen_when_muted = true

# Network
[[block]]
block = "net"
format_alt = "$icon {$ssid $signal_strength $frequency|Wired connection} "

# Time
[[block]]
block = "time"
interval = 60
[block.format]
  full = "$timestamp.datetime(f:'%a, %b %d  %I:%M%P', l:es_MX)"
  short = "$timestamp.datetime(f:'%I:%M%P', l:es_MX)"
