[theme]
  theme = "plain"

[theme.overrides]
idle_bg = "#1e1e1e"
idle_fg = "#e6d9b8"
info_bg = "#1e1e1e"
info_fg = "#e6d9b8"
good_bg = "#1e1e1e"
good_fg = "#e6d9b8"
warning_bg = "#1e1e1e"
warning_fg = "#e6d9b8"
critical_bg = "#1e1e1e"
critical_fg = "#cc0000"
separator = ""
separator_bg = "auto"
separator_fg = "auto"

[icons]
  icons = "awesome6"

# Battery
[[block]]
block = "battery"
format = " $icon $percentage"
full_format = "$icon"
empty_format = " $icon $percentage"
charging_format = " $icon $percentage  "
not_charging_format = "$icon $percentage  "
missing_format = ""
interval = 10

# Backlight
[[block]]
block = "backlight"

# Bluetooth
#[[block]]
#block = "bluetooth"
#format = "$icon $percentage"
#disconnected_format = "$icon"

# Volume
[[block]]
block = "sound"
show_volume_when_muted = true

# Network
[[block]]
block = "net"
format = " ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
format_alt = "{$ssid $signal_strength $frequency|Wired connection} "

# Time
[[block]]
block = "time"
interval = 60
timezone = "America/Mexico_City"
[block.format]
  full = " $timestamp.datetime(f:'%^a, %^b %d  %I:%M%P', l:es_MX)"
  short = " $timestamp.datetime(f:'%I:%M%P', l:es_MX)"
